// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxezqkyotnruoxxbirgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4ZXpxa3lvdG5ydW94eGJpcmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNjg2NzIsImV4cCI6MjA2MTc0NDY3Mn0.USGNVwW6KLfHs3wkRh9E2LWr5XiG1RToMWS6Qy_vyCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);